name: CI
on:
  # temporary disable workflows

  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # - name: Prepare dist
      #   run: mkdir -p brutallycss/dist

      - name: Install lightningcss (most recent/optimal and support CSS nesting)
        run: npm install -g lightningcss-cli

      - name: Install clean-css (to minify into one single file afterwards)
        run: npm install -g clean-css-cli

      - name: Bundle + minify CSS
        run: lightningcss --targets ">= 0.25%" --minify  css/**/*.css -d dist/

      - name: Minify in one single CSS file
        run: cleancss -o dist/main.min.css dist/*.css --remove-inlined-files

      - name: Install html-minifier
        run: npm install -g html-minifier

      - name: Minify HTML files into dist
        run: |
          for file in *.html; do
            html-minifier \
              --collapse-whitespace \
              --remove-comments \
              --remove-optional-tags \
              --remove-redundant-attributes \
              --remove-script-type-attributes \
              --remove-tag-whitespace \
              --use-short-doctype \
              "$file" > "dist/$(basename "$file")"
          done

      - name: Copy static assets to dist
        run: |
          rsync -av --delete \
            --exclude "css/" \
            --exclude "dist/" \
            --exclude ".github/" \
            --exclude "*.html" \
            ./ \
            ./dist/

      - name: Debug
        run: |
          ls -la dist
          ls -la .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: brutallycss-dist
          path: dist
  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [minify]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: brutallycss-dist
          path: dist

      - name: Debug
        run: ls -la dist

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy build with rsync
        run: rsync -avz --delete ./dist ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/brutallycss.com/
