name: Build & Deploy
on:
  # temporary disable workflows

  pull_request:
    branches:
      - disabled

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install clean-css
        run: npm install -g clean-css-cli

      - name: Build and minify CSS
        run: cleancss -o dist/main.min.css css/**/*.css --remove-inlined-files

      - name: Install html-minifier
        run: npm install -g html-minifier-terser

      - name: Minify HTML files
        run: |
          for file in *.html; do
            html-minifier \
              --collapse-whitespace \
              --remove-comments \
              --remove-optional-tags \
              --remove-redundant-attributes  \
              --remove-script-type-attributes  \
              --remove-tag-whitespace  \
              --use-short-doctype  \
              --minify-css true \
              -o "$file" "$file" 
          done
